version: 2.0.{build}

branches:
  only:
  - master

skip_tags: true

clone_folder: c:\gopath\src\github.com\andreluzz\go-travisci-example

environment:
  GOPATH: c:\gopath

install:
- cmd: >-
    echo %PATH%

    echo %GOPATH%

    set PATH=%GOPATH%\bin;c:\go\bin;%PATH%

    go version

    go env

    go get -v -t -d ./...

build_script:
- cmd: go build -ldflags "-X main.version=$(appveyor_build_version)" -o _buildOutput\go-travisci-example_v2.exe -i .

test_script:
- ps: >-
    go list ./...
    
    go test -race -coverprofile=profile.out -covermode=atomic github.com/andreluzz/go-travisci-example/app
    
    cat profile.out >> coverage.txt
    
    rm profile.out
    
    go test -race -coverprofile=profile.out -covermode=atomic github.com/andreluzz/go-travisci-example/xml

    cat profile.out >> coverage.txt
    
    rm profile.out

    $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH

    Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh

    bash codecov.sh -f "coverage.txt" -t 6c33dd73-92a1-4527-a4e7-994c3c1a8e1f

artifacts:
- path: _buildOutput\go-travisci-example_v2.exe
  name: binary
- path: config.xml
  name: config

deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: go-travisci-example-$(appveyor_build_version)
  description: 'This is a release of CI integration correcting bugs and adding improvements.'
  auth_token:
    secure: eis8p27PKzPZRUHXV+2FrJ4cNkAj8DN/LCkLbktucyzmmCt2JzKA2CLqWRFH1Wkh
  artifact: binary,config
  force_update: true
